### PR TITLE
Make Reagent devcards update on atom changes (another try)

### PR DESCRIPTION
**Pull request by maio**
Do not call fn directly, let reagent handle that. This way it will react
to atom changes properly.

### CODE REVIEW

**Comment by bhauman** [comment]
This looks good!  You have ensured that this is working the way you want it too?

**Comment by bhauman** [comment]
My main concern is sub components not changing as expected because of closure capture.  I'm don't use Reagent so I'm having to rely on your testing and experiments.

**Comment by maio** [comment]
It seems to work fine. Example:

```clojure
(defn sub-component [state]
  [:div "Sub-component:" (:counter @state)])

(defcard-rg reagent-deref-test
  (fn [state _]
    [:div
     [:div "Here:" (:counter @state)]
     [sub-component state]
     [:button {:on-click #(swap! state update :counter inc)} "inc"]])

  (reagent/atom {:counter 0})
  {:inspect-data true})
```

### Before this fix

reagent-before

### After

reagent-after

**Comment by bhauman** [comment]
Cool!  I'm still wondering about what happens when you Change the subcomponent.  Do the change propagate?

**Comment by actionshrimp** [comment]
Was having a similar issue with a card not re-rendering on state change, tested devcards built from master locally and this commit seems to have fixed it. Would it be possible to cut a release with this in?

Many thanks!

**Pull request merged**
